spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
  graphql:
    graphiql:
      enabled: true


